language: go
go:
  - 1.8
script:
  - go test -race -v -bench=.
notifications:
  email: false
services:
  - rabbitmq
addons:
  apt:
    packages:
      - lsb-release
      - python-dev
      - python-virtualenv
      - gcc
      - libaugeas0
      - libssl-dev
      - libffi-dev
      - ca-certificates
      - rsyslog
      - libltdl3-dev
  mariadb: "10.1"
  hosts:
    - example.com
    - example
    - boulder
    - boulder-rabbitmq
    - boulder-mysql
env:
  global:
    - PATH=$HOME/bin:$PATH # protoc gets installed here
    - GO15VENDOREXPERIMENT=1
before_install:
  - git clone --depth=1 https://github.com/letsencrypt/boulder.git $HOME/gopath/src/github.com/letsencrypt/boulder
before_script:
  - |
    # make required changes to boulder rules and start boulder
    set -e
    go get bitbucket.org/liamstask/goose/cmd/goose
    cd $GOPATH/src/github.com/letsencrypt/boulder
    ./test/setup.sh
    make
    ./start.py &
    BOUDLER_PID=$!
    cd $TRAVIS_BUILD_DIR
after_script:
  - kill $BOUDLER_PID
